name: pdf_viewer_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.1.1
  flutter:
    sdk: flutter
  loading_animation_widget: ^1.2.1
  syncfusion_flutter_pdfviewer: ^26.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/thumbnails/thumbnail_sk.png
