final List<Map<String, dynamic>> pdfList = [
  {
    'title': 'Flutter Development Guide',
    'author': 'John Doe',
    'pages': 200,
    'thumbnail': 'assets/thumbnails/thumbnail_sk.png',
    'fileSize': '5 MB',
    'lastOpened': '2024-08-10',
    'isFavorite': true,
  },
  {
    'title': 'Introduction to Dart',
    'author': 'Jane Smith',
    'pages': 150,
    'thumbnail': 'assets/thumbnails/thumbnail_sk.png',
    'fileSize': '3 MB',
    'lastOpened': '2024-08-12',
    'isFavorite': false,
  },
  {
    'title': 'Advanced Flutter Widgets',
    'author': 'Alex Johnson',
    'pages': 250,
    'thumbnail': 'assets/thumbnails/thumbnail_sk.png',
    'fileSize': '7 MB',
    'lastOpened': '2024-08-05',
    'isFavorite': true,
  },
  {
    'title': 'State Management in Flutter',
    'author': 'Emily White',
    'pages': 180,
    'thumbnail': 'assets/thumbnails/thumbnail_sk.png',
    'fileSize': '4 MB',
    'lastOpened': '2024-08-11',
    'isFavorite': false,
  },
  {
    'title': 'Flutter Animations',
    'author': 'Michael Green',
    'pages': 120,
    'thumbnail': 'assets/thumbnails/thumbnail_sk.png',
    'fileSize': '2.5 MB',
    'lastOpened': '2024-08-08',
    'isFavorite': true,
  },
];
